name: Trigger auto deployment for foobar

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/foobar-AutoDeployTrigger-e0f65696-bf3f-40ca-b1ff-2b08d89aec0b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FOOBAR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FOOBAR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FOOBAR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.FOOBAR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FOOBAR_REGISTRY_PASSWORD }}
          containerAppName: foobar
          resourceGroup: group0
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


